```ini
$font = Monospace

general {
    hide_cursor = false
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

# =========================
# WALLPAPER
# =========================

background {
    monitor =
    path = $HOME/.config/hypr/wallpapers/lock.png
    blur_passes = 0
    blur_size = 0
}

# =========================
# USERNAME
# =========================

label {
    monitor =
    text = BeastMaster64

    font_size = 28
    font_family = $font
    color = rgba(0, 0, 0, 1.0)

    position = 0, 80
    halign = center
    valign = center
}

# =========================
# TIME
# =========================

label {
    monitor =
    text = $TIME

    font_size = 72
    font_family = $font
    color = rgba(255, 255, 255, 1.0)

    position = 0, 190
    halign = center
    valign = top
}

# =========================
# DATE
# =========================

label {
    monitor =
    text = cmd[update:60000] echo "$(date '+%A, %d %B %Y')"

    font_size = 28
    font_family = $font
    color = rgba(255, 255, 255, 1.0)

    position = 0, 285
    halign = center
    valign = top
}

# =========================
# PASSWORD
# =========================

input-field {
    monitor =

    size = 20%, 5%
    outline_thickness = 3

    # FULL BLACK PASSWORD BOX
    inner_color = rgba(0, 0, 0, 1.0)
    outer_color = rgba(0, 0, 0, 1.0)

    # Keep authentication feedback
    check_color = rgba(0, 255, 153, 1.0)
    fail_color = rgba(255, 102, 51, 1.0)

    # White text inside black box
    font_color = rgba(255, 255, 255, 1.0)

    fade_on_empty = false
    rounding = 15

    font_family = $font
    placeholder_text = Input password...
    fail_text = $PAMFAIL

    dots_spacing = 0.3

    position = 0, -20
    halign = center
    valign = center
}

# =========================
# SESSION BUTTON
# =========================

label {
    monitor =
    text = SESSION

    font_size = 20
    font_family = $font
    color = rgba(255, 255, 255, 1.0)

    position = 0, -100
    halign = center
    valign = bottom

}
onclick = ~/.config/hypr/scripts/session-selector.sh
